services:
  init:
    image: alpine
    command: ["sh", "-c", "mkdir -p /dev/shm/mxl/ffmpeg"]
    volumes:
      - type: bind
        source: /dev/shm
        target: /dev/shm
    restart: no

  ffmpeg-source:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:latest
    depends_on:
      - init
    restart: unless-stopped
    entrypoint: "/opt/bin/ffmpeg"
    volumes:
      - type: bind
        source: ./
        target: /tmp/
      - type: bind
        source: /dev/shm/mxl/ffmpeg
        target: /domain
    command:
      - "-hide_banner"
      - "-re"
      - "-stream_loop"
      - "-1"
      - "-i"
      - "/tmp/demo_reel.ts"
      - "-map"
      - "0:v"
      - "-vf"
      - "drawtext=text='CBC/RC - BREAKING NEWS - MXL is coming to FFmpeg!':x='mod(w-t*200, w+tw)-tw':y=h-th-50:fontfile=/usr/share/fonts/truetype/freefont/FreeSansBold.ttf:fontcolor=white:fontsize=100:shadowcolor=red:shadowx=5:shadowy=5"
      - "-c:v"
      - "v210"
      - "-f"
      - "mxl"
      - "-video_flow_id"
      - "fe781cad-8a82-4b8e-a3c2-f833c70ac73e"
      - "/domain"
      - "-map"
      - "0:a"
      - "-c:a"
      - "pcm_f32le"
      - "-f"
      - "mxl"
      - "-audio_flow_id"
      - "ca28b9ff-9d44-41ba-9c88-99329e7995a6"
      - "/domain"

  ffmpeg-probe:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:latest
    depends_on:
      - ffmpeg-source
    entrypoint: "/opt/bin/ffprobe"
    volumes:
      - type: bind
        source: /dev/shm/mxl/ffmpeg
        target: /domain
    command: "-hide_banner \
      /domain/fe781cad-8a82-4b8e-a3c2-f833c70ac73e.mxl-flow"
    restart: no

  ffmpeg-dest-v:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:latest
    depends_on:
      - mediamtx
      - ffmpeg-source
    restart: unless-stopped
    network_mode: "host"
    entrypoint: "/opt/bin/ffmpeg"
    volumes:
      - type: bind
        source: /dev/shm/mxl/ffmpeg
        target: /domain
    command: "-hide_banner \
      -f mxl -i /domain/fe781cad-8a82-4b8e-a3c2-f833c70ac73e.mxl-flow \
      -vf 'scale=1280:720,format=yuv420p' \
      -c:v libx264 -preset fast -tune zerolatency -b:v 5M \
      -x264-params 'sliced-threads=1:sync-lookahead=0' \
      -f rtsp -rtsp_transport tcp rtsp://${MEDIAMTX_HOST:-127.0.0.1}:8554/ffmpeg-v"

  ffmpeg-dest-a:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:latest
    depends_on:
      - mediamtx
      - ffmpeg-source
    restart: unless-stopped
    network_mode: "host"
    entrypoint: "/opt/bin/ffmpeg"
    volumes:
      - type: bind
        source: /dev/shm/mxl/ffmpeg
        target: /domain
    command: "-hide_banner \
      -f mxl -i /domain/ca28b9ff-9d44-41ba-9c88-99329e7995a6.mxl-flow \
      -c:a libopus -b:a 64k \
      -f rtsp -rtsp_transport tcp rtsp://${MEDIAMTX_HOST:-127.0.0.1}:8554/ffmpeg-a"

  ffmpeg-dest:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:latest
    depends_on:
      - mediamtx
      - ffmpeg-source
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - type: bind
        source: /dev/shm/mxl/ffmpeg
        target: /domain
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 40
    environment:
      # --- Required Variables ---
      - MXL_DOMAIN=/domain
      - VIDEO_ID=fe781cad-8a82-4b8e-a3c2-f833c70ac73e
      - AUDIO_ID=ca28b9ff-9d44-41ba-9c88-99329e7995a6
      - RTSP_URL=rtsp://${MEDIAMTX_HOST:-127.0.0.1}:8554/ffmpeg
      #  --- Optional ---
      - FFMPEG_LOGLEVEL=info
      - FFMPEG_MODE=cpu
      - FFMPEG_RT_PRIORITY=40
      - RTSP_TRANSPORT=tcp
      - V_BLOCKING=0
      - A_GRAIN_INDEX_INIT=1
      - V_GRAIN_INDEX_INIT=1

  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MTX_RTSPTRANSPORTS=tcp
    ports:
      - "8554:8554"
      - "8322:8322"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
      - "9997:9997"
    volumes:
      - ../mediamtx.yml:/mediamtx.yml:ro
