# Permissions from https://github.com/OpenVisualCloud/Media-Transport-Library/tree/main/docker#run-with-dpdk
# But IPC_LOCK doesn't seem necessary.
# see ../../docs/st_2110.md for detailsO
services:
  ffmpeg-st2110-to-mxl-v:
    image: ghcr.io/cbcrc/ffmpeg-mxl-imtl:latest
    container_name: ffmpeg-st2110-to-mxl-v
    network_mode: "host"
    devices:
      - /dev/vfio/ # Intel NIC
      - /dev/infiniband/ # Mellanox/Nvidia
    cap_add:
      - SYS_NICE
      - NET_ADMIN # Mellanox: requested by rdma-core/libverbs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/run/imtl:/var/run/imtl
      - /dev/shm/mxl/st2110:/domain
    entrypoint: ["/usr/local/bin/st2110.py"]
    command:
      - "/opt/bin/ffmpeg"
    environment:
      - DIRECTION=rx
      - PCI_ADDR=${RX_PCI_ADDR}
      - LOCAL_IFACE_IP=${LOCAL_IFACE_IP}
      - VIDEO_MCAST_IP=${RX_VIDEO_MCAST_IP}
      - MXL_DOMAIN=/domain
      - VIDEO_FLOW_ID=${VIDEO_FLOW_ID}

  ffmpeg-mxl-to-st2110-v:
    image: ghcr.io/cbcrc/ffmpeg-mxl-imtl:latest
    container_name: ffmpeg-mxl-to-st2110-v
    depends_on:
      - ffmpeg-mxl-to-rtp
    network_mode: "host"
    devices:
      - /dev/vfio/
      - /dev/infiniband/
    cap_add:
      - SYS_NICE
      - NET_ADMIN # Mellanox: requested by rdma-core/libverbs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /var/run/imtl:/var/run/imtl
      - /dev/shm/mxl/st2110:/domain
    entrypoint: ["/usr/local/bin/st2110.py"]
    command:
      - "/opt/bin/ffmpeg"
    environment:
      - DIRECTION=tx
      - MXL_DOMAIN=/domain
      - VIDEO_FLOW_ID=${VIDEO_FLOW_ID}
      - PCI_ADDR=${TX_PCI_ADDR}
      - LOCAL_IFACE_IP=${LOCAL_IFACE_IP}
      - VIDEO_MCAST_IP=${TX_VIDEO_MCAST_IP}

  ffmpeg-mxl-to-rtp:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:latest
    container_name: ffmpeg-mxl-to-rtp
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - type: bind
        source: /dev/shm/mxl/st2110/
        target: /domain
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 40
    environment:
      # --- Required Variables ---
      - MXL_DOMAIN=/domain
      - VIDEO_ID=${VIDEO_FLOW_ID}
      - RTSP_URL=rtsp://${MEDIAMTX_HOST:-127.0.0.1}:8554/st2110
      #  --- Optional ---
      - FFMPEG_LOGLEVEL=info
      - FFMPEG_MODE=cpu
      - FFMPEG_RT_PRIORITY=40
      - RTSP_TRANSPORT=tcp
