# syntax=docker/dockerfile:1.6

# Development image containing build tools and dependencies.

FROM ubuntu:24.04

ARG UID
ARG GID
ARG EXTENDED

RUN test -n "$UID" && test -n "$GID" || \
    (echo "ERROR: UID and GID build args are required" && exit 1)

COPY . /scripts

RUN echo "container" > /run/ffmpeg-build-context
RUN /scripts/setup-env-all.sh
RUN if [ "$EXTENDED" = "1" ]; then /scripts/setup-env-ffmpeg-extended.sh; fi

RUN set -e; \
    if ! getent group "${GID}" >/dev/null; then \
        groupadd -g "${GID}" builder; \
    fi; \
    if ! id -u "${UID}" >/dev/null 2>&1; then \
        useradd -m -u "${UID}" -g "${GID}" builder; \
    fi

ENV UID=${UID}
ENV GID=${GID}

RUN install -d -o ${UID} -g ${GID} /build
RUN install -d -o ${UID} -g ${GID} /src

USER ${UID}:${GID}
WORKDIR /src
CMD ["bash", "-li"]
