volumes:
  mxl-domain:
    driver: local
    driver_opts:
      device: none
      type: tmpfs
      o: nosuid,strictatime,uid=1000,gid=1000,mode=0755

services:
  ffmpeg-source:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:v1.0.0
    restart: unless-stopped
    entrypoint: "/opt/bin/ffmpeg"
    volumes:
      - type: bind
        source: ./
        target: /tmp/
      - type: volume
        source: mxl-domain
        target: /domain
    command: "-hide_banner \
      -re -stream_loop -1 -i /tmp/demo_reel.ts \
      -c:v v210 \
      -f mxl -video_flow_id fe781cad-8a82-4b8e-a3c2-f833c70ac73e /domain"

  ffmpeg-probe:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:v1.0.0
    depends_on:
      - ffmpeg-source
    entrypoint: "/opt/bin/ffprobe"
    volumes:
      - type: volume
        source: mxl-domain
        target: /domain
    command: "-hide_banner \
      /domain/fe781cad-8a82-4b8e-a3c2-f833c70ac73e.mxl-flow"
    restart: no

  ffmpeg-dest:
    image: ghcr.io/cbcrc/ffmpeg-mxl-prod:v1.0.0
    depends_on:
      - mediamtx
      - ffmpeg-source
    restart: unless-stopped
    network_mode: "host"
    entrypoint: "/opt/bin/ffmpeg"
    volumes:
      - type: volume
        source: mxl-domain
        target: /domain
    command: "-hide_banner \
      -i /domain/fe781cad-8a82-4b8e-a3c2-f833c70ac73e.mxl-flow \
      -vcodec libx264 -preset fast -tune zerolatency \
      -f rtsp rtsp://127.0.0.1:8554/mxlstream"

  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MTX_RTSPTRANSPORTS=tcp
    ports:
      - "8554:8554"
      - "8322:8322"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
      - "9997:9997"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
